# Generated by Django 4.2.11 on 2024-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name_plural': 'boardgames'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'players'},
        ),
    ]
