# Generated by Django 4.2.11 on 2024-03-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_alter_boardgame_options_alter_player_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
